### ISSUE TITLE
Recurring TypeError

### ISSUE THREAD

**Issue by capndave** [andreabreu-me/gatsby-plugin-prettier-eslint#10]
I'm getting the following error after installing `gatsby-plugin-prettier-eslint` on a gatsby site, on every `npm run develop`. Any idea what's up? Code [here](https://github.com/capndave/davethompsonisme)

```javascript
ERROR

TypeError: Expected a string, got object
    at isTypeSync (/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/prettier/third-party.js:10578:11)
    at getDirectorySync (/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/prettier/third-party.js:10631:60)
    at ExplorerSync.searchSync (/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/prettier/third-party.js:10785:66)
    at _resolveConfig (/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/prettier/index.js:24900:50)
    at Function.resolveConfig.sync (/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/prettier/index.js:24930:42)
    at PrettierProcessor._format (/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/gatsby-plugin-prettier-eslint/dist/watcher/PrettierProcessor.js:39:57)
    at /home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/gatsby-plugin-prettier-eslint/dist/watcher/PrettierProcessor.js:71:30
    at Array.forEach (<anonymous>)
    at PrettierProcessor.process (/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/gatsby-plugin-prettier-eslint/dist/watcher/PrettierProcessor.js:70:10)
    at PrettierEslintWatcher.fullScan
(/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/gatsby-plugin-prettier-eslint/dist/watcher/PrettierEslintWatcher.js:53:30)
    at PrettierEslintWatcher.start
(/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/gatsby-plugin-prettier-eslint/dist/watcher/PrettierEslintWatcher.js:106:12)
    at Object.onCreateWebpackConfig (/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/gatsby-plugin-prettier-eslint/dist/gatsby-node.js:56:15)
    at runAPI (/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/gatsby/src/utils/api-runner-node.js:430:22)
    at Promise.catch.decorateEvent.pluginName (/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/gatsby/src/utils/api-runner-node.js:581:13)
    at Promise._execute (/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/home/dthompson/Code/davethompsonisme-gatsby/davethompsonisme/node_modules/bluebird/js/release/promise.js:518:18)
```

**Comment by capndave** [comment]
It looks like the `filePath` parameter being passed on line 10576 of prettier's `third-party.js` is null, when Prettier runs on startup. Setting `initialScan: false` in `gatsby-config.js` seems to resolve this. Let me know if you see any issues that need to be addressed here @andreabreu-me

**Comment by capndave** [comment]
Actually this is still a problem - changing a file causes prettier to run which again fails at the same spot in `third-party.js` (because `filePath` is null.) The local gatsby web server then crashes

**Comment by capndave** [comment]
Turns out you **must** have a prettier config to avoid this error in prettier. Fixed by adding a prettier config by one of the methods documented [here](https://prettier.io/docs/en/configuration.html)
